[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --cache-dir /tmp/pip-cache -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python neethi.py"
